language: python

cache:
  pip: true
  apt: true
  directories:
  - ~/mne_data/

sudo: false
dist: trusty


matrix:
  include:
    - env: TEST=standard
      os: linux
      python: '3.6'


before_install:
    # Instal miniconda
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      fi;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - SRC_DIR=$(pwd)


install:
    # Create the python environment ;
    - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION numpy pip cython matplotlib;
    - source activate testenv
    # Testing dependencies
    - pip install codecov pytest pytest-cov;
    # Install graphpype
    - cd ${SRC_DIR}
    - pip install -e .
    - pip install flake8

before_script:
    - wget https://deim.urv.cat/~sergio.gomez/download.php?f=radatools-5.0-linux64.tar.gz -O /tmp/radatools-5.0-linux64.tar.gz
    - tar -xvf /tmp/radatools-5.0-linux64.tar.gz -C /tmp
    - export PATH="$PATH:/tmp/radatools-5.0-linux64/Network_Tools"
    - export PATH="$PATH:/tmp/radatools-5.0-linux64/Network_Properties"
    - export PATH="$PATH:/tmp/radatools-5.0-linux64/Communities_Detection"
    - export PATH="$PATH:/tmp/radatools-5.0-linux64/Communities_Tools"

script:

    # Run test with coverage
    - if [[ "${TEST}" == "standard" ]]; then
        py.test --cov;
      fi;

    - flake8 --count graphpype

notifications:
    email: false


after_success:
    # Code coverage
    - if [ "${TEST}" == "standard" ]; then
        codecov;
      fi
